title:              yun-ss 개인블로그
email:              yunseung_lee@korea.ac.kr
description:        Deep Learning, Computer Vision, Natural Language Processing 공부자료
author:             Yunseung Lee
baseurl:            ""
url:                "https://yun-ss97.github.io"

# Social Profiles
#twitter_username:   
github_username:    yun-ss97
#facebook_username:  
#instagram_username:  
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
